### ISSUE TITLE
net standart 

### ISSUE THREAD

**Issue by danijerez** [Sarel-Esterhuizen/GroqSharp#1]
Thank you for creating this groq client, I had a question, wouldn't it be more advisable to use the net standart sdk instead of dotnet 8? so it would be more compatible

**Comment by Sarel-Esterhuizen** [comment]
Thank you for bringing this up!

The project originated from a few hours of experimenting with Groq, and as such I did not optimize for compatibility. 
Although it's feasible to adjust it to target a lower version of .NET, I utilized several language features exclusive to .NET 8.0, which complicates direct compatibility.

I am definitely considering a future project to downport it to an earlier version for broader compatibility. Contributions are always welcome, so if anyone has the bandwidth and interest to tackle this task, I would greatly appreciate pull requests!
